#!/usr/bin/env ruby


$: << File.join(File.dirname(__FILE__), '..', 'vendor', 'gems', 'json-1.2.0', 'lib')
$: << File.join(File.dirname(__FILE__), '..', 'vendor', 'gems', 'json-1.2.0', 'lib', 'json', 'add')
$: << File.join(File.dirname(__FILE__), '..', 'vendor', 'gems', 'eventmachine-0.12.10-java', 'lib')
$: << File.join(File.dirname(__FILE__), '..', 'vendor', 'gems', 'eventmachine-0.12.10-java', 'ext')


require File.join(File.dirname(__FILE__), '..', 'vendor', 'gems', 'juggernaut-0.5.8', 'lib', 'juggernaut')
# require File.join(File.dirname(__FILE__), '..', 'vendor', 'gems', 'json-1.1.3', 'lib', 'json.rb')

Juggernaut::Runner.run
